// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srmrqtrsgrifjfppjmpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNybXJxdHJzZ3JpZmpmcHBqbXBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MjEzNzYsImV4cCI6MjA3MjM5NzM3Nn0.OreuZPPRULcLVDMJimDj2lWCIUvjslyXg9H8lMyp-BQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});