// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elqdcivvunyndnbhsewk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVscWRjaXZ2dW55bmRuYmhzZXdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5NjUxODMsImV4cCI6MjA4ODU0MTE4M30.5Spe4-gaOF1BALVNn_3qHnkYFlWFLTOaANWSJ-XWGeY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});